apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: denyrecommendationhandler
spec:
  compiledAdapter: denier
  params:
    status:
      code: 7
      message: Not allowed
---
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: denyrecommendationrequest
spec:
  compiledTemplate: checknothing
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: denyrecommendation
spec:
  match: destination.labels["app"] == "recommendation" 
  actions:
  - handler: denyrecommendationhandler
    instances: [ denyrecommendationrequest ]